# Generated by Django 5.1.7 on 2025-03-29 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
    
    ]
