# Generated by Django 5.1.6 on 2025-04-06 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_collection_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='data',
            new_name='date',
        ),
    ]
